name: Android Build

on: pull_request

jobs:
  Restore_cache_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{runner.os}}-gradle-${{ hashFiles('**/*.gradle*')}}
          restore-keys: |
            ${{runner.os}}-gradle-

  Set_up_jdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

  Test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run test
        run: ./gradlew test

  UI_test_job:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        uses: ReactiveCircus/android-emulator-runner@v2.14.3
        with:
          api-level: 29
          script: ./gradlew connectedCheck

      - name: generate report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: app/build/reports/coverage/debug

      - name: Download Test Reports Folder
        uses: actions/download-artifact@v2
        with:
          name: report
          path: app/build/reports/coverage/debug

      - name: Upload Test Report
        uses: codecov/codecov-action@v1
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
#            run:  bash <(curl -s https://codecov.io/bash) -f "app/build/reports/coverage/debug/report.xml"

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build project
        run: ./gradlew assemble



#      - name: Upload Apk
#        uses: actions/upload-artifact@v2
#        with:
#          name: apk
#          path: app/build/outputs/apk/debug/**.apk




